import { DateTime, Interval } from 'luxon';
import { verify } from 'whurdal-word-verifier';

const wordList: string[] = [
    'KNIFE',
    'YOUTH',
    'UNION',
    'HAVOC',
    'DRAMA',
    'ABOUT',
    'INDEX',
    'BRAVO',
    'MAGIC',
    'PEACH',
    'FUDGE',
    'STICK',
    'WRONG',
    'SHARP',
    'FAULT',
    'GRIFT',
    'VOICE',
    'CRYPT',
    'FAITH',
    'CHEAP',
    'ABOVE',
    'ALOHA',
    'STUDY',
    'SUPER',
    'LAYER',
    'SUGAR',
    'FORTE',
    'SPANK',
    'VIRUS',
    'DELTA',
    'MUSIC',
    'CHEWY',
    'NOISE',
    'BLOCK',
    'APPLE',
    'WASTE',
    'THEME',
    'LIGHT',
    'ABUSE',
    'TONES',
    'WHITE',
    'ALIKE',
    'UPSET',
    'COURT',
    'QUEEN',
    'PRIDE',
    'WRITE',
    'VIDEO',
    'URBAN',
    'SHOCK',
    'NORTH',
    'GRAND',
    'SPITE',
    'MARSH',
    'GIANT',
    'THETA',
    'POWER',
    'DOUBT',
    'SWING',
    'DRAFT',
    'RAISE',
    'FRESH',
    'RAPID',
    'VAGUE',
    'POUND',
    'AWFUL',
    'CREAM',
    'TULLE',
    'CRAZY',
    'JUDGE',
    'CHONK',
    'PARSE',
    'CIRCA',
    'PRIME',
    'THICK',
    'SCENE',
    'PIANO',
    'EXTRA',
    'UNITY',
    'CHIEF',
    'WORLD',
    'ORDER',
    'SHANK',
    'VALOR',
    'POINT',
    'FARCE',
    'SPIRE',
    'TOWER',
    'GUSTO',
    'MOIST',
    'CRANE',
    'SPIKE',
    'LEARN',
    'CHOIR',
    'XEROX',
    'QUANT',
    'MANOR',
    'EMAIL',
    'SERVE',
    'CABLE',
    'STEAM',
    'PRINT',
    'MONEY',
    'BIDET',
    'SPINE',
    'GIRTH',
    'FIBER',
    'SMART',
    'GHAST',
    'TOTAL', // TODAY
    'ULTRA',
    'DIODE',
    'POISE',
    'BUILD',
    'GROIN',
    'FOCAL',
    'SCONE',
    'AXION',
    'INEPT',
    'FIRST',
    'MARIA',
    'SHAFT',
    'HYPER',
    'MOTIF',
    'BOSON',
    'SPACE',
    'AVANT',
    'MEDIA',
    'CHORE',
    'SHINE',
    'ORGAN',
    'MONTH',
    'DRIVE',
    'TROPE',
    'BATIK',
    'LADLE',
    'DRAWN',
    'ELOPE',
    'LEVEL',
    'PANEL',
    'FLUID',
    'GOURD',
    'ALBUM',
    'LINER',
    'QUERY',
    'INERT',
    'FIGHT',
    'CANON',
    'EMOTE',
    'DECAY',
    'BURST',
    'STYLO',
    'FARAD',
    'BELLE',
    'TUPLE',
    'STEEL',
    'MOTOR',
    'CRISP',
    'LARGE',
    'GLUON',
    'CLOSE',
    'FOCUS',
    'MOVIE',
    'EAGER',
    'CHAIN',
    'SLICE',
    'TRUNK',
    'INLAY',
    'ANION',
    'RATIO',
    'CLOUD',
    'SHORT',
    'OPTIC',
    'TETRA',
    'DUPLE',
    'CREST',
    'STAFF',
    'JOULE',
    'CHIME',
    'TONIC', 
    'PHOTO',
    'APART',
    'MESON',
    'CRIMP',
    'OUTRO',
    'TENOR',
    'QUIRK',
    'STORY',
    'ALPHA',
    'PRIMO',
    'MIGHT',
    'FIFTH',
    'DEPTH',
    'LYRIC',
    'HERTZ',
    'AURAL',
    'SLASH',
    'CARET',
    'TODAY',
    'HEART',
    'MORPH',
    'TWERP',
    'BASIC',
    'SHEAR',
    'HEXAD',
    'PITCH',
    'ANGEL',
    'TRICK',
    'SHOWN',
    'RADIX',
    'MEZZO',
    'PROTO',
    'SLIDE',
    'VERSE',
    'CRAFT',
    'ANODE',
    'SCORE',
    'TESLA',
    'EBONY',
    'WATCH',
    'SOLAR',
    'BLOKE',
    'ALLOY',
    'TEMPO',
    'GENUS',
    'PHASE',
    'METER',
    'PEDAL',
    'RETRO',
    'WHOLE',
    'CABIN',
    'TONAL',
    'TRIAD',
    'INTRO',
    'SCALE',
    'MOLAR',
    'CRUST',
    'RANGE',
    'FRUNK',
    'GUIDE',
    'MAJOR',
    'STERN',
    'LOVER',
    'BLIND',
    'CHORD',
    'ALARM',
    'PRISM',
    'VALUE',
    'ISSUE',
    'DEATH',
    'PENNY',
    'FUGUE',
    'THEFT',
    'SCREW',
    'QUARK'
];

let nonSowpodsAcceptedWords: string[] = ['CHONK', 'GRATZ', 'FRUNK', 'PROTO'];

export function verifyWordsInList(): string[] | null {
    let rejectedWords: string[] = [];
    let words: string[] = [];
    for (let i = 0; i < wordList.length; i++) {
        if (words.includes(wordList[i])) {
            rejectedWords.push(wordList[i] + ' DUPLICATE')
        }
        // Reject any words with 3 dupe letters
        for(const letter of wordList[i]) {
            if(wordList[i].split(letter).length > 3) {
                rejectedWords.push(wordList[i]);
                break;
            }
        }
        words.push(wordList[i])
        if (!wordIsValid(wordList[i])) {
            rejectedWords.push(wordList[i])
        }
    }

    return rejectedWords;
}

export function wordIsValid(word: string): boolean {
    word = word.toUpperCase();
    return (verify(word) || nonSowpodsAcceptedWords.includes(word)) && word.length === 5;
}

export function getDaysSinceBeginning(): number {
    const startDate = DateTime.local(2022, 2, 26);
    const daysSince = Interval.fromDateTimes(startDate, DateTime.local());
    const daysSinceInt = daysSince.length('days');

    return Math.floor(daysSinceInt);
}

export function getTimeUntilTomorrow(): string {
    let rightNow = DateTime.local();
    let tomorrow = DateTime.local().plus({ days: 1 }).startOf('day');

    return tomorrow.diff(rightNow).toFormat('hh:mm:ss');
}

export function getTodaysWord(): string {
    let daysSinceBeginning = getDaysSinceBeginning();
    return wordList[(daysSinceBeginning % wordList.length)];
}
